const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let page=0,cid=null,offset=0,summary;
async function api(path,data){const r=await fetch('/api/'+path,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});const j=await r.json();if(!r.ok)throw Error(j.error);return j;}
function table(head,rr){return '<table><thead><tr>'+head.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rr.map(r=>'<tr>'+r.map(x=>'<td>'+x+'</td>').join('')+'</tr>').join('')+'</tbody></table>';}
function message(e){$('error').hidden=false;$('error').textContent=e.message;}
async function refresh(){try{summary=await api('summary');const s=summary.selection,v=summary.validation;const verdict=summary.verdict;$('status').textContent=verdict?verdict.verdict+' · RF: '+verdict.selected_timely+'/11 timely incidents, '+verdict.selected_reviews+' investigations. Corrected IF: '+verdict.comparator_timely+'/11, '+verdict.comparator_reviews+' investigations. RF exceeds the predeclared matched-cost limit by one investigation.':s?`Selected ${s.scorer} / ${s.representation} / ${s.gate} / ${s.queue_variant}. Later validation ${v?'consumed':'not yet evaluated'}.`:'Preparing corrected feature cache; no improvement claim.';
$('results').innerHTML=v?table(['System / gate / policy','Daily capacity','Actual reviews','Current positives','Context positives','Timely incidents ≤72h','Official incidents'],v.frontier.filter(r=>r.selected||r.system==='C_IF/fit/max_cooldown/1').map(r=>[esc(r.system+(r.selected?' / selected':'')),r.capacity,r.reviews,r.current_positive_reviews,r.context_positive_reviews,r.timely_incidents+'/'+r.incidents_available,r.official_incidents+'/'+r.incidents_available])):'';
const r=summary.run;$('runtime').textContent=r?`${r.id} / ${summary.running?'running (checkpoint '+r.status+')':r.status} / committed records=${r.events_processed.toLocaleString()}/${r.events_total.toLocaleString()} / admissions=${summary.case_count}`:'No selected replay yet';$('start').disabled=!summary.ready||summary.running||r?.status==='completed';$('new').disabled=!summary.ready||summary.running;$('pause').disabled=!summary.running;await cases();}catch(e){message(e);}}
async function cases(){const r=await api('cases?'+new URLSearchParams({search:$('search').value,status:$('filter').value,offset:page*20}));$('cases').innerHTML=table(['Model / identity','Decision','Score','Reopening','Evidence','Review'],r.rows.map(c=>[`<button class="text-button" data-case="${esc(c.case_id)}">${esc(c.detector+' / '+c.identity_id)}</button>`,esc(c.decision_time),Number(c.score).toFixed(4),c.reopening?esc(c.reopening_reason):'No',c.evidence_total,esc(c.review.status)]));$('page').textContent=`${page+1} / ${Math.max(1,Math.ceil(r.total/20))}`;$('previous').disabled=!page;$('next').disabled=(page+1)*20>=r.total;document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>{cid=b.dataset.case;offset=0;inspect();});}
function close(){ $('drawer').hidden=true;$('backdrop').hidden=true;document.body.classList.remove('modal-open');document.querySelectorAll('body>header,body>main').forEach(e=>e.inert=false);}
async function inspect(){try{const r=await api('case?'+new URLSearchParams({id:cid,offset})),c=r.case;$('drawer').hidden=false;$('backdrop').hidden=false;document.body.classList.add('modal-open');document.querySelectorAll('body>header,body>main').forEach(e=>e.inert=true);$('close').focus();$('title').textContent=c.detector+' / '+c.identity_id;
$('case-content').innerHTML=`<p class="mono">${esc(c.model_version)} / ${esc(c.feature_contract)} / gate=${esc(c.calibration_version)} / policy=${esc(c.queue_version)}</p><p class="mono">decision=${esc(c.decision_time)} score=${Number(c.score).toFixed(4)} / gate=${Number(c.threshold).toFixed(4)}</p><p class="trace-note">${esc(r.policy)}</p><details><summary>Admission / reopening evidence</summary><pre>${esc(JSON.stringify({reopening:c.reopening,preceding_case:c.preceding_case,new_qualifying_ids:c.new_qualifying_ids,score_history:c.score_history,presented_families:c.presented_families},null,2))}</pre></details><h2>Closed-day measurements</h2>${r.observations.map(o=>`<details><summary>${esc(o.day+' / '+o.role+' / metadata='+o.metadata_month)}</summary><pre>${esc(JSON.stringify({actual_transformed_model_inputs:o.transformed_inputs,counts:o.counts,magnitude:o.features,signed_percentiles:o.percentiles,peer_features:o.peer_features,reference:o.reference,percentile_reference:o.percentile_reference,peer_reference:o.peer_reference},null,2))}</pre></details>`).join('')}<h2>Original evidence (${r.evidence_total})</h2><div class="pagination"><button id="evprev" class="button">Previous evidence</button><span>${offset+1}–${Math.min(offset+50,r.evidence_total)}</span><button id="evnext" class="button">Next evidence</button></div><div class="table-wrap">${table(['Time / source ID','Relationship','Original fields'],r.events.map(e=>[esc(e.timestamp)+'<small>'+esc(e.event_id)+'</small>',esc(e.relationship),`<details><summary>${esc(e.source+' / row '+e.row_number)}</summary><pre>${esc(JSON.stringify(e.original,null,2))}</pre></details>`]))}</div><h2>Versioned analyst feedback</h2><div class="toolbar"><select id="reviewstatus" aria-label="V4 case status">${['new','in_review','resolved','dismissed'].map(x=>`<option ${r.review.status===x?'selected':''}>${x}</option>`).join('')}</select><select id="disposition" aria-label="V4 case disposition">${['unreviewed','benign','suspicious','confirmed','needs_context'].map(x=>`<option ${r.review.disposition===x?'selected':''}>${x}</option>`).join('')}</select></div><textarea id="note" aria-label="V4 review note" maxlength="4000">${esc(r.review.note||'')}</textarea><button class="button" id="save">Save v4 review</button><p id="saved" role="status"></p>`;
$('evprev').disabled=!offset;$('evnext').disabled=offset+50>=r.evidence_total;$('evprev').onclick=()=>{offset-=50;inspect();};$('evnext').onclick=()=>{offset+=50;inspect();};$('save').onclick=async()=>{try{await api('review',{id:cid,version:r.review.version,status:$('reviewstatus').value,disposition:$('disposition').value,note:$('note').value});$('saved').textContent='Saved';$('save').disabled=true;cases();}catch(e){message(e);}};}catch(e){message(e);}}
$('close').onclick=close;$('backdrop').onclick=close;document.addEventListener('keydown',e=>{if(e.key==='Escape')close();});['new','start','pause'].forEach(a=>$(a).onclick=async()=>{try{await api(a,{});refresh();}catch(e){message(e);}});$('refresh').onclick=refresh;$('previous').onclick=()=>{page--;cases();};$('next').onclick=()=>{page++;cases();};$('search').onchange=$('filter').onchange=()=>{page=0;cases();};setInterval(()=>{if($('drawer').hidden)refresh();},5000);refresh();
